/*
 * Copyright 2022 Nightingale Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

import { Room, Rack, RackDevice, RoomLayout, CMDBAsset, RoomStatistics, RackStatistics } from './types';

// Mock 机房数据
export const mockRooms: Room[] = [
  {
    id: 1,
    name: '核心机房A',
    code: 'ROOM-A-001',
    address: '北京市朝阳区xxx',
    area: 500,
    type: '自建',
    level: 'T3',
    status: 'active',
    contact: '张三',
    contactPhone: '13800138000',
    description: '核心机房描述',
    rackCount: 50,
    deviceCount: 500,
    uUsageRate: 0.75,
    powerUsageRate: 0.65,
  },
  {
    id: 2,
    name: '核心机房B',
    code: 'ROOM-B-001',
    address: '北京市海淀区xxx',
    area: 300,
    type: '租赁',
    level: 'T2',
    status: 'active',
    contact: '李四',
    contactPhone: '13900139000',
    description: '核心机房B描述',
    rackCount: 30,
    deviceCount: 300,
    uUsageRate: 0.6,
    powerUsageRate: 0.55,
  },
  {
    id: 3,
    name: '备用机房',
    code: 'ROOM-C-001',
    address: '北京市丰台区xxx',
    area: 200,
    type: '托管',
    level: 'T2',
    status: 'maintenance',
    contact: '王五',
    contactPhone: '13700137000',
    description: '备用机房描述',
    rackCount: 20,
    deviceCount: 200,
    uUsageRate: 0.4,
    powerUsageRate: 0.35,
  },
];

// Mock 机柜数据
export const mockRacks: Rack[] = [
  {
    id: 1,
    roomId: 1,
    name: 'A01',
    code: 'RACK-A01',
    positionX: 10.5,
    positionY: 5.2,
    rotation: 0,
    totalU: 42,
    usedU: 15,
    powerCapacity: 10.0,
    powerUsed: 3.5,
    networkPorts: 24,
    networkPortsUsed: 20,
    status: 'active',
    description: '机柜A01',
    roomName: '核心机房A',
    deviceCount: 8,
  },
  {
    id: 2,
    roomId: 1,
    name: 'A02',
    code: 'RACK-A02',
    positionX: 15.0,
    positionY: 5.2,
    rotation: 0,
    totalU: 42,
    usedU: 20,
    powerCapacity: 10.0,
    powerUsed: 5.0,
    networkPorts: 24,
    networkPortsUsed: 18,
    status: 'active',
    description: '机柜A02',
    roomName: '核心机房A',
    deviceCount: 10,
  },
  {
    id: 3,
    roomId: 1,
    name: 'A03',
    code: 'RACK-A03',
    positionX: 19.5,
    positionY: 5.2,
    rotation: 0,
    totalU: 42,
    usedU: 10,
    powerCapacity: 10.0,
    powerUsed: 2.0,
    networkPorts: 24,
    networkPortsUsed: 12,
    status: 'active',
    description: '机柜A03',
    roomName: '核心机房A',
    deviceCount: 5,
  },
  {
    id: 4,
    roomId: 2,
    name: 'B01',
    code: 'RACK-B01',
    positionX: 10.0,
    positionY: 5.0,
    rotation: 0,
    totalU: 42,
    usedU: 25,
    powerCapacity: 10.0,
    powerUsed: 6.0,
    networkPorts: 24,
    networkPortsUsed: 22,
    status: 'active',
    description: '机柜B01',
    roomName: '核心机房B',
    deviceCount: 12,
  },
  {
    id: 5,
    roomId: 2,
    name: 'B02',
    code: 'RACK-B02',
    positionX: 15.0,
    positionY: 5.0,
    rotation: 0,
    totalU: 42,
    usedU: 18,
    powerCapacity: 10.0,
    powerUsed: 4.5,
    networkPorts: 24,
    networkPortsUsed: 16,
    status: 'active',
    description: '机柜B02',
    roomName: '核心机房B',
    deviceCount: 9,
  },
  {
    id: 6,
    roomId: null,
    name: 'C01',
    code: 'RACK-C01',
    totalU: 42,
    usedU: 0,
    powerCapacity: 10.0,
    powerUsed: 0,
    networkPorts: 24,
    networkPortsUsed: 0,
    status: 'active',
    description: '未分配机柜',
    deviceCount: 0,
  },
];

// Mock 机柜设备数据
export const mockRackDevices: RackDevice[] = [
  {
    id: 1,
    rackId: 1,
    deviceId: 101,
    deviceName: '服务器-001',
    startU: 1,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-01',
  },
  {
    id: 2,
    rackId: 1,
    deviceId: 102,
    deviceName: '服务器-002',
    startU: 3,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-02',
  },
  {
    id: 3,
    rackId: 1,
    deviceId: 103,
    deviceName: '交换机-001',
    startU: 5,
    heightU: 1,
    deviceType: 'switch',
    status: 'online',
    installDate: '2024-01-03',
  },
  {
    id: 4,
    rackId: 1,
    deviceId: 104,
    deviceName: '服务器-003',
    startU: 6,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-04',
  },
  {
    id: 5,
    rackId: 1,
    deviceId: 105,
    deviceName: '服务器-004',
    startU: 8,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-05',
  },
  {
    id: 6,
    rackId: 1,
    deviceId: 106,
    deviceName: '服务器-005',
    startU: 10,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-06',
  },
  {
    id: 7,
    rackId: 1,
    deviceId: 107,
    deviceName: '服务器-006',
    startU: 12,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-07',
  },
  {
    id: 8,
    rackId: 1,
    deviceId: 108,
    deviceName: '服务器-007',
    startU: 14,
    heightU: 1,
    deviceType: 'server',
    status: 'offline',
    installDate: '2024-01-08',
  },
  {
    id: 9,
    rackId: 2,
    deviceId: 201,
    deviceName: '服务器-201',
    startU: 1,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-10',
  },
  {
    id: 10,
    rackId: 2,
    deviceId: 202,
    deviceName: '服务器-202',
    startU: 3,
    heightU: 2,
    deviceType: 'server',
    status: 'online',
    installDate: '2024-01-11',
  },
];

// Mock 机房布局数据
export const mockRoomLayouts: Record<number, RoomLayout> = {
  1: {
    id: 1,
    roomId: 1,
    canvasScale: 1.0,
    canvasX: 0,
    canvasY: 0,
    rackLayouts: [
      { rackId: 1, x: 10.5, y: 5.2, rotation: 0 },
      { rackId: 2, x: 15.0, y: 5.2, rotation: 0 },
      { rackId: 3, x: 19.5, y: 5.2, rotation: 0 },
    ],
  },
  2: {
    id: 2,
    roomId: 2,
    canvasScale: 1.0,
    canvasX: 0,
    canvasY: 0,
    rackLayouts: [
      { rackId: 4, x: 10.0, y: 5.0, rotation: 0 },
      { rackId: 5, x: 15.0, y: 5.0, rotation: 0 },
    ],
  },
};

// Mock CMDB 设备数据
export const mockCMDBAssets: CMDBAsset[] = [
  {
    id: 301,
    gid: 10,
    status: 'online',
    tags: ['env=prod', 'team=ops'],
    tags_maps: { env: 'prod', team: 'ops' },
    data: {
      name: '服务器-301',
      ip: '192.168.1.101',
      category: 'server',
      manufacturer: 'Dell',
      model_name: 'PowerEdge R740',
    },
    asset_type: 'server',
  },
  {
    id: 302,
    gid: 10,
    status: 'online',
    tags: ['env=prod', 'team=ops'],
    tags_maps: { env: 'prod', team: 'ops' },
    data: {
      name: '服务器-302',
      ip: '192.168.1.102',
      category: 'server',
      manufacturer: 'HP',
      model_name: 'ProLiant DL380',
    },
    asset_type: 'server',
  },
  {
    id: 303,
    gid: 11,
    status: 'online',
    tags: ['env=prod'],
    tags_maps: { env: 'prod' },
    data: {
      name: '交换机-301',
      ip: '192.168.1.201',
      category: 'switch',
      manufacturer: 'Cisco',
      model_name: 'Catalyst 2960',
    },
    asset_type: 'switch',
  },
];

// Mock 统计数据
export const mockRoomStatistics: Record<number, RoomStatistics> = {
  1: {
    rackTotal: 50,
    rackUsed: 45,
    rackAvailable: 5,
    deviceTotal: 500,
    uTotal: 2100,
    uUsed: 1575,
    uUsageRate: 0.75,
    powerTotal: 500.0,
    powerUsed: 325.0,
    powerUsageRate: 0.65,
    alarmCount: 5,
  },
  2: {
    rackTotal: 30,
    rackUsed: 28,
    rackAvailable: 2,
    deviceTotal: 300,
    uTotal: 1260,
    uUsed: 756,
    uUsageRate: 0.6,
    powerTotal: 300.0,
    powerUsed: 165.0,
    powerUsageRate: 0.55,
    alarmCount: 2,
  },
};

export const mockRackStatistics: Record<number, RackStatistics> = {
  1: {
    deviceCount: 8,
    uUsed: 15,
    uAvailable: 27,
    uUsageRate: 0.357,
    powerUsed: 3.5,
    powerAvailable: 6.5,
    powerUsageRate: 0.35,
    networkPortsUsed: 20,
    networkPortsAvailable: 4,
  },
  2: {
    deviceCount: 10,
    uUsed: 20,
    uAvailable: 22,
    uUsageRate: 0.476,
    powerUsed: 5.0,
    powerAvailable: 5.0,
    powerUsageRate: 0.5,
    networkPortsUsed: 18,
    networkPortsAvailable: 6,
  },
};

